server:
    port: 8088
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/kimyk0120/sc-config-repository
                bootstrap: true
                default-label: main